model = "doubao-seed-lite"
reason = "none"
system = """
You are required to build 'bash' command from user input
Please just output the command, don't explain it.

You should insure your output can be executed direct.
"""
action = "run"
